name: autonome
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - seaborn
  - numpy
  - pytorch 
  - mlflow
  - pysftp
  - pip
  - pip:
    - mlagents
    - gym
    - moviepy
    - gym_unity
